### ISSUE TITLE
Support other decorator names

### ISSUE THREAD

**Issue by abierbaum** [goloveychuk/tsruntime#1]
Thanks for the awesome project.  I have been looking for something like this for a long time.  Very excited to use it.  One question though.

Is there a way to support other decorator names?

In our code base we already have a couple decorators that mark a class that I want to see tsruntime information on.  Instead of requiring everyone to remember the Reflective decorator as well, I would like a way to use our decorators but still tell tsruntime to include the details.

Looking at: https://github.com/goloveychuk/tsruntime/blob/master/src/transformer.ts#L148 it looks like the code explicitly looks for a decorator called `Reflective`.  Any ideas how to make this a bit more extensible?

A couple of random ideas:
 
1) Allow users to mark their own decorators as being "reflective" through a property on the decorator

```
function UserReflective(target: any) {
   // Do great things
}
UserReflective._isReflective = true;

@UserReflective
class MyClass {

}
```
the the code in the transformer could check if the decorator function has a property "_isRefective" set on it.  If so then consider that decorator as one to add tsruntime information.

2) Allow configuration setting with names of decorators to consider

Not sure where to put this configuration setting so it can be passed on...

**Comment by goloveychuk** [comment]
yea it could be done with adding some symbol to function. 

import {ReflectiveSymbol} from 'tsruntime'
function CustomReflective() {

}
CustomReflective[ReflectiveSymbol] = true
But to resolve this symbol required some internal typescript api. I'm new to it, but looks like we need https://github.com/Microsoft/TypeScript/blob/2150a7796b0dfe83c5286755410e0fd1646ed86c/src/compiler/types.ts#L2720

So this required collaboration from typescript team. The great boost whould be if typescript team move emitting metadata logic to custom transformer, which uses only public methods.

Maybe I'll try to do this next weekends. For now, if you're able to make changes for this lib, I recommend not to use it on production. Since it have many problems, e.g. not all types are emitted. Any, arrays, objects and so on.

**Comment by goloveychuk** [comment]
I looked on ts sources, I really should much to do to have solid library
https://github.com/Microsoft/TypeScript/blob/2150a7796b0dfe83c5286755410e0fd1646ed86c/src/compiler/transformers/ts.ts#L1681
e.g. here they used internal api
https://github.com/Microsoft/TypeScript/blob/2150a7796b0dfe83c5286755410e0fd1646ed86c/src/compiler/transformers/ts.ts#L1806

**Comment by goloveychuk** [comment]
so for know, I you really want to use it, I recommend to rename function to `Reflective`

**Comment by abierbaum** [comment]
@goloveychuk That makes sense.

What would you think about either passing an optional configuration object to get the transformer function?  So basically turn the main exported call into a builder function that can take some options and return the final transformer function?

Alternatively I could add a method to the transformer module that could be called after import to configure settings separately from getting the custom transformer. 

Seems like this may be a reasonable way to add configuration / setting support to the code.

**Comment by goloveychuk** [comment]
yea, first option is ok. If you could pls make pr, with optional args (with default value) to transformer function

**Comment by abierbaum** [comment]
@goloveychuk See: https://github.com/goloveychuk/tsruntime/pull/3 and tell me what you think.

Note: I know this project isn't quite production ready, but it already provides me with a few things we have been wanting for a long time.  Thank you so much for putting it together.

**Comment by goloveychuk** [comment]
@abierbaum yea, this is good. Merged. I'll look this weekends what can I do for advanced resolving.

**Comment by abierbaum** [comment]
@goloveychuk Thanks.  I was going to look into some resolution a bit today, but I will wait and see what you come up with so I don't step on your toes and add similar things.

**Comment by abierbaum** [comment]
@goloveychuk Could you bump the version and push a new version to npm?

**Comment by goloveychuk** [comment]
@abierbaum I can but I recommend make git pull and npm link (and in ci use your fork) since I'll make many modifications while you adapt this lib in your project.

**Comment by abierbaum** [comment]
@goloveychuk Understood.  For our CI process it is tough to use a git fork directly, but I can pin a specific npm release version with yarn no problem.  

The only part I am going to use at the start is the info about whether a property is nullable, so if you change the API as you add more information I can easily adjust my code later.

Aside: One other suggestion would be to add a function like "getPropertyType(target: Object, propertyKey?: string | symbol)" to the types.ts file so people don't have to know they have to look at the class prototype to get the type info for properties.

**Comment by goloveychuk** [comment]
@abierbaum yea, I'll add it.
Also I'm thinking about some MetaData repository, which would have all metadata info and some helpers-functions, stored in objects. Without using typescript Metadata.decorate

**Comment by abierbaum** [comment]
@goloveychuk Sounds like a great idea with the metadata repository.  Would love to see the metadata in structured objects to make it easier to explore and understand.
