### ISSUE TITLE
Classes with properties that have interface types cause generated code to fail

### ISSUE THREAD

**Issue by abierbaum** [goloveychuk/tsruntime#12]
Ran into a big stumbling block.  The way Reference types are generated into the code, tsruntime assumes the identifier can be used at runtime.  For example to refer to a class name.  This breaks when a property is given a type that is an interface since interfaces have no runtime symbol.  Because of this the generated code causes reference errors and can't bootstrap.

Something like this will cause the failure:

```
interface IGeom {
    coordinates: any;
}

@Reflective
class LocationClass {
   geomProp:  IGeom;
}
```

Spent the better part of the afternoon trying to find a way around this and haven't found a good one yet.  The best idea I have seen is in tslint here: https://github.com/palantir/tslint/blob/master/src/rules/noMisusedNewRule.ts#L46  but I can't find a way to do something similar in a transformation.

Any ideas?

**Comment by abierbaum** [comment]
One idea I had overnight on this.  

assume kind A is class and kind B is interface.  Then if the generated code did something like this:
```
(IGeom) ? {kind: A, type: IGeom} | {kind: B, type: "IGeom"}
```

It still doesn't quite work because the references will generate an error, but if `IGeom` could be represented as a lookup in the local scope then maybe it could work....

**Comment by goloveychuk** [comment]
since from AST perspective Interface and class references are the same, this requires using additional compiler api. EmitResolver or Typechecker. Will look this weekends.
And yes, interface not available on runtime, so it should be "interfaceName" as string literal

**Comment by abierbaum** [comment]
The other one I ran into is "type" aliases.  They come through as the alias name instead of the thing being aliased.  Not sure how you want to handle that one since the alias could refer to any combination of types, interface, unions, etc.  I could see an argument for short circuting the alias and exposing the actual parts it aliases.

**Comment by goloveychuk** [comment]
fixed it in master. 
but this don't work with Awesome typescript loader

**Comment by goloveychuk** [comment]
look at master. don't forget to npm i.
I'm using fork of awe typescript loader

**Comment by goloveychuk** [comment]
also I think I should remove 'optional' flag.
From typechecker perspective it's enum with undefined.

**Comment by goloveychuk** [comment]
also I made reflective factory. look at custom_decorator.spec.ts

**Comment by goloveychuk** [comment]
should be fixed
