### ISSUE TITLE
Class with reference to external class type generates failing code

### ISSUE THREAD

**Issue by abierbaum** [goloveychuk/tsruntime#13]
Similar to: https://github.com/goloveychuk/tsruntime/issues/12

If you have a file with a class like: 

```
// external_classes.ts
export class ExternalClass {
   a: string = '';
}
```

And then a reflective class in a file like:

```
import { ExternalClass } from './external_classes';

@Reflective
class UseExternalClass {
   extRef: ExternalClass;
}
```
then the generated code in the module with the reflective class with try to reference `ExternalClass` by name, but it isn't available in the scope because the compiler and webpack did not know it should be.

**Comment by abierbaum** [comment]
The more I think about this one the more I think this is a bug in either webpack or awesome-typescript-loader.  I think it related to https://github.com/angular/angular-cli/issues/5651 as well.  Basically someone is deciding to ignore the import and not put it into the generated code because it doesn't look like it is needed.  But then a decorator comes across that needs the code and that usage isn't picked up.

**Comment by goloveychuk** [comment]
yes, I know about this problem. Workaround for now is console.log(ExternalClass). 
Problem here is that symbolTable, which have all type references and aliases is filling before CustomTransformers are executing. So alias I created manually doesn't count. 
Looks like this would require changing typescript main codebase.

**Comment by abierbaum** [comment]
That is unfortunate.  I was hoping there may be some automated way to make this happen.   Could be a good way to post an issue to the typescript project and let them know about your effort here.  Maybe one of them will be interested in helping out.

**Comment by goloveychuk** [comment]
let me try to hack it. And if it's impossible - I'll write to typescript team. I'm sure they'll help with it. 
They already added one method to emitResolver for type metadata emitting.

**Comment by goloveychuk** [comment]
https://github.com/Microsoft/TypeScript/issues/15816

**Comment by goloveychuk** [comment]
should be fixed
