### ISSUE TITLE
how to configure for usage with typescript in node.js?

### ISSUE THREAD

**Issue by capaj** [goloveychuk/tsruntime#14]
the readme shows how to use this project in webpack, but I was wondering-can it be used in node.js?

**Comment by philipp-sorin** [comment]
Dono exactly, but you can play with https://github.com/TypeStrong/ts-node, they have transformers support

**Comment by goloveychuk** [comment]
I rewrote `tsruntime`, updated docs, now you can use `ttypescript`.
