### ISSUE TITLE
tsruntime transformer doesn't run using steps in README

### ISSUE THREAD

**Issue by abierbaum** [goloveychuk/tsruntime#2]
I have been trying to get the tsruntime transformation to run following the steps in the README.md file but have had no luck.  When the code is generated, I do not see anything added to the code. 

To test this further I created a minimal sample project with test code based upon the example in README.md.

Please see: https://github.com/abierbaum/test_tsruntime

To test the build and generation, just run:

> npm run test

This will build the code and then try to run it with node.  It throws an exception when running about not having reflective information available.  Also if you check the dist/ directory you will see the bundled code does not have any transformed code.

I feel I must be doing something very simple wrong but can't find it.  Any pointers?

I used a webpack.config.js of:

```
const getCustomTransformers = require('tsruntime/dist/transformer').default;

module.exports = {
  entry: './src/main.ts',

  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx']
  },

  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [
          {
            loader: 'awesome-typescript-loader',
            options: {
              getCustomTransformers
            }
          }
        ]
      }
    ]
  },

  output: {
    filename: 'dist/bundle.js'
  }
}
```

**Comment by goloveychuk** [comment]
@abierbaum I updated readme.

**Comment by abierbaum** [comment]
@goloveychuk Thanks!!!  That helped and makes a lot more sense.

I updated https://github.com/abierbaum/test_tsruntime to use this in the build.

Unfortunately now I get an exception when trying to call getType on StatsModel the say you do in the README.md example.  Is there something else I am missing here?

See: https://github.com/abierbaum/test_tsruntime/blob/master/src/main.ts#L22

**Comment by goloveychuk** [comment]
yea, it should be
getType(Constr) to get type info for class
and
getType(Constr.prototype, "prop") for property.
this is how Reflect.metadata works

**Comment by abierbaum** [comment]
@goloveychuk Thanks.  That works great.  I updated the example with the changes.
