### ISSUE TITLE
Docs out of date

### ISSUE THREAD

**Issue by IonelLupu** [goloveychuk/tsruntime#24]
I've tried to test this library but I encountered some problems when running it (version 3.0.0): ` Cannot find module 'tsruntime/transformer.js'`

The fix is to update the tsconfig.json plugins key into this:

`{ "transform": "tsruntime/dist/transform/transformer.js", "type": "program" }`

This is the file structure of the library on NPM.

**Comment by goloveychuk** [comment]
thanks, updated
