### ISSUE TITLE
Test suite to help with transformer development?

### ISSUE THREAD

**Issue by abierbaum** [goloveychuk/tsruntime#4]
While I was thinking about how to add support for a couple new pieces of reflective information I started thinking about how to add a test suite to iterate and verify that everything was working.

General idea was:
  * Add a karma configuration that uses webpack to compile spec.ts files
  * Setup the webpack config to use the local transformation
  * Build a set of spec files using jamsine that locally definite the entities that are decorated to be reflective
  * Have the tests use tsruntime/types interface to verify that everything is exposed as expected
  * Add an npm script that watches the source code and when it changes runs the build for the transformer into /dist followed by the tests using karma

This would also provide some nice examples of how to use the interface to get at the reflective information.

Anyway, if this is something of interest let me know and I could try a first pass at adding a skeleton of this idea to try out.

**Comment by goloveychuk** [comment]
yes, it would be useful in further development. Fell free to create PR for this. 
I'll provide a little script which runs this tsruntime transformer, using Program Api. Without usage webpack and awesome ts loader.

**Comment by goloveychuk** [comment]
Also I want to discover typescript plugin api, maybe it's possible to add transformer as plugin via tsconfig.json

**Comment by abierbaum** [comment]
@goloveychuk Based on what I saw in the threads in typescript repo sounds like they don't want to allow plugins to be enabled through tsconfig.json.  So that may not be possible for quite a while.  That said, the webpack integration is great and should help a lot of people.

**Comment by abierbaum** [comment]
I have been working on this in some spare time.  I don't quite have it working yet.  I still haven't found a good example of how to make typescript, karma, and webpack all play nice together that doesn't have angular or some other pieces in the mix.  I will try to bang away at it a bit more later this week.

**Comment by abierbaum** [comment]
@goloveychuk I got something working this afternoon and just put it up for a pull request. https://github.com/goloveychuk/tsruntime/pull/5

Let me know what you think.

**Comment by goloveychuk** [comment]
look at master. Could you fix travis build? Should add installing chrome or move to phantomjs

**Comment by abierbaum** [comment]
I haven't use TravisCI, but this seems related: https://github.com/travis-ci/travis-ci/issues/7650

I will see what I can find.

**Comment by abierbaum** [comment]
@goloveychuk See: https://github.com/goloveychuk/tsruntime/pull/6
