### ISSUE TITLE
All types

### ISSUE THREAD

**Issue by goloveychuk** [goloveychuk/tsruntime#7]
Next step would be to write tests for all possible prop types. 
@abierbaum

**Comment by abierbaum** [comment]
@goloveychuk Are you still actively working on the project?  I may have some time in the next few weeks to work on it a bit more and see if it can do the things I need now.

**Comment by goloveychuk** [comment]
@abierbaum I finished writing thi library since it solves my problem. So currently - somtimes I'm finding corner cases and make little fixes. Nothing major. You could help with corner cases and tests.

**Comment by goloveychuk** [comment]
or maybe it could be developed in some other direction. Just don't know what problems/tasks other devs have.

**Comment by abierbaum** [comment]
I will take a closer look.  The more I think about it the more I think my use cases may just require the user to pass more information into the decorators I am using to collect class metadata.

**Comment by goloveychuk** [comment]
Added new tests.
So for now library solving my problem. 
If somebody want to consider moving to other directions (e.g. move all reflection data to storage) - feel free to create new issue.
