### ISSUE TITLE
Changelog and tags

### ISSUE THREAD

**Issue by abierbaum** [goloveychuk/tsruntime#8]
@goloveychuk I know this may sound picky, but what do you think about having a Changelog section in the readme or a CHANGELOG.md file so there is a place to document what changed between released versions.  I think this would help me and others understand when a release is pushed to npm and what it has in it.

Similarly, what do you think about using git tags to tag the versions to match the version numbers pushed to npm.  A lot of projects do that and I find it very helpful for seeing exactly what code goes along with a released version of the project.

On a related note, could you make a new release with some of the recent updates?

**Comment by goloveychuk** [comment]
yea, once it'd be stabilized I'll do it.
Do npm can autopublish from git tags?

**Comment by abierbaum** [comment]
@goloveychuk It probably can, but I have always done it manually.  If you find a good way to do it I would love to see how you do it.

As far as releases, I will make a branch in my repo to push built versions up to github and use it from there for now.  I just needed something I can reference from package.json that has the dist files so I can get it working on a project in CI.  (ie. outside of my local dev box)

**Comment by goloveychuk** [comment]
ok, `npm version minor` makes great work.

**Comment by goloveychuk** [comment]
I published as 1.1.0

**Comment by goloveychuk** [comment]
@abierbaum I have crushed headless chrome, on macos, 58.0.3029.110 (64-bit)
What chrome you have?

**Comment by abierbaum** [comment]
$ google-chrome --version
Google Chrome 58.0.3029.96

Running on Linux 64-bit.

I haven't tried it on OSX.

**Comment by goloveychuk** [comment]
writing change log now.
https://github.com/goloveychuk/tsruntime/releases
